# Generated by Django 4.0 on 2023-03-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_count',
            field=models.BooleanField(default=False),
        ),
    ]
